services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8082:8081"
    volumes:
      - /media/wd5tb/downloads/metube:/downloads
    environment:
        - AUDIO_DOWNLOAD_DIR:/media/wd5tb/downloads/metube/music